var KEY="medpark_yield_skin_v1";
var state=loadState(),currentDetailLot=null,lotDraftImages={actual:[],map:[]};
var analysisCtx={lotId:null,photoId:null,img:null,points:[],showMask:true,mask:null,last:null};
var titles={dashboard:["Skin 수율 대시보드","원재료에서 최종제품까지 단계별 수율과 Lot 흐름을 확인합니다."],lots:["원재료 Lot 관리","입고면적, 사진, 실측면적, 두께와 현재 공정단계를 관리합니다."],process:["공정 데이터 입력","단위와 Lot 성격이 바뀌는 관리 포인트만 기록합니다."],rules:["제품 규격 Master","최종제품별 사용 가능한 Powder Grade 기준을 관리합니다."]};
var stageNames={sderm:"S Derm 생산",fdadm:"FD / ADM",cutting:"Cutting Mill",freezer:"Freezer Mill",final:"최종제품"};
function loadState(){try{var x=JSON.parse(localStorage.getItem(KEY));if(x&&x.lots&&x.events){x.lots.forEach(function(l){l.actualPhotos=l.actualPhotos||[];l.mapPhotos=l.mapPhotos||[]});return x}}catch(e){}return {lots:[],events:[]}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function n(v){var x=parseFloat(v);return isNaN(x)?0:x}
function fmt(v,d){return n(v).toLocaleString("ko-KR",{maximumFractionDigits:d==null?1:d})}
function pct(a,b){return b>0?a/b*100:0}
function today(){return new Date().toISOString().slice(0,10)}
function id(p){return p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,6)}
function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]})}
function lotEvents(lid){return state.events.filter(function(e){return e.lotId===lid}).sort(function(a,b){return String(a.date).localeCompare(String(b.date))})}
function latestStage(lid){var es=lotEvents(lid);return es.length?stageNames[es[es.length-1].type]:"입고"}
function findLot(lid){return state.lots.find(function(x){return x.id===lid})}
function openModal(i){document.getElementById(i).classList.add("show")}
function closeModal(i){document.getElementById(i).classList.remove("show")}
function photoCount(l){return (l.actualPhotos||[]).length+(l.mapPhotos||[]).length}
function analyzedPhotoCount(l){return (l.actualPhotos||[]).filter(function(p){return p.analysis&&p.analysis.areaCm2}).length}
function buildThumb(i){return '<div class="photo-thumb"><img src="'+i.dataUrl+'"><div><b>'+esc(i.name)+'</b><small>'+(i.analysis&&i.analysis.areaCm2?"분석 "+fmt(i.analysis.areaCm2)+" cm²":"미분석")+'</small></div></div>'}
function toDataURL(file,maxSize,quality){return new Promise(function(resolve){var fr=new FileReader();fr.onload=function(){var im=new Image();im.onload=function(){var sc=Math.min(1,maxSize/Math.max(im.width,im.height)),w=Math.round(im.width*sc),h=Math.round(im.height*sc),c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(im,0,0,w,h);resolve({id:id("img"),name:file.name,dataUrl:c.toDataURL("image/jpeg",quality||.8),width:w,height:h,createdAt:new Date().toISOString(),analysis:null})};im.src=fr.result};fr.readAsDataURL(file)})}
async function handleFiles(input,type){for(const f of Array.from(input.files||[])){lotDraftImages[type].push(await toDataURL(f,1400,.8))}renderUploadPreviews();input.value=""}
function renderUploadPreviews(){actualPreview.innerHTML=lotDraftImages.actual.map(buildThumb).join("");mapPreview.innerHTML=lotDraftImages.map.map(buildThumb).join("")}
document.querySelectorAll(".nav button").forEach(function(btn){btn.onclick=function(){document.querySelectorAll(".nav button").forEach(function(x){x.classList.remove("active")});btn.classList.add("active");var v=btn.dataset.view;document.querySelectorAll(".view").forEach(function(x){x.classList.remove("active")});document.getElementById(v).classList.add("active");pageTitle.textContent=titles[v][0];pageSub.textContent=titles[v][1];if(v==="process")updateProcessSide()}})
document.querySelectorAll("[data-close]").forEach(function(b){b.onclick=function(){closeModal(b.dataset.close)}})
function showLotModal(){lotDraftImages={actual:[],map:[]};["fLot","fBank","fInbound","fMeasured","fMap","fTMin","fTMax","fNote"].forEach(function(i){document.getElementById(i).value=""});fDate.value=today();renderUploadPreviews();openModal("lotModal")}
newLotTop.onclick=showLotModal;newLotBtn.onclick=showLotModal;
fActualPhotos.onchange=function(){handleFiles(this,"actual")};fMapPhotos.onchange=function(){handleFiles(this,"map")};
saveLot.onclick=function(){var lot=fLot.value.trim(),bank=fBank.value.trim(),date=fDate.value,inb=n(fInbound.value);if(!lot||!bank||!date||inb<=0){alert("Lot, 조직은행, 입고일, 입고면적을 입력해 주세요.");return}if(state.lots.some(function(x){return x.code===lot})){alert("이미 등록된 Lot 번호입니다.");return}state.lots.push({id:id("lot"),code:lot,bank:bank,date:date,inboundArea:inb,measuredArea:n(fMeasured.value),mapArea:n(fMap.value),tMin:n(fTMin.value),tMax:n(fTMax.value),note:fNote.value.trim(),actualPhotos:lotDraftImages.actual.slice(),mapPhotos:lotDraftImages.map.slice(),createdAt:new Date().toISOString()});closeModal("lotModal");saveState()};
function renderDashboard(){var inbound=state.lots.reduce(function(s,x){return s+n(x.inboundArea)},0),measured=state.lots.reduce(function(s,x){return s+n(x.measuredArea)},0),photoLots=state.lots.filter(function(l){return analyzedPhotoCount(l)>0}).length,adm=state.events.filter(function(e){return e.type==="fdadm"}).reduce(function(s,e){return s+n(e.data.admWeight)},0),powder=state.events.filter(function(e){return e.type==="freezer"}).reduce(function(s,e){return s+n(e.data.g70)+n(e.data.g100)+n(e.data.g500)},0),finalQty=state.events.filter(function(e){return e.type==="final"}).reduce(function(s,e){return s+n(e.data.qty)},0);kInbound.textContent=fmt(inbound)+" cm²";kMeasured.textContent=fmt(measured)+" cm²";kMeasuredSub.textContent=inbound?"입고 대비 "+fmt(pct(measured,inbound))+"%":"입고 대비 -";kPhotoLots.textContent=fmt(photoLots,0)+" 건";kAdm.textContent=fmt(adm)+" g";kPowder.textContent=fmt(powder)+" g";kFinal.textContent=fmt(finalQty,0)+" ea";var banks={};state.lots.forEach(function(l){banks[l.bank]=banks[l.bank]||{i:0,m:0};banks[l.bank].i+=n(l.inboundArea);banks[l.bank].m+=n(l.measuredArea)});bankBars.innerHTML=Object.keys(banks).sort().map(function(k){var p=pct(banks[k].m,banks[k].i);return '<div class="bar-row"><b>'+esc(k)+'</b><div class="bar"><i style="width:'+Math.min(100,p)+'%"></i></div><span>'+fmt(p)+'%</span></div>'}).join("")||'<div class="empty">데이터가 없습니다.</div>';recentEvents.innerHTML=state.events.slice().sort(function(a,b){return String(b.createdAt).localeCompare(String(a.createdAt))}).slice(0,5).map(function(e){var l=findLot(e.lotId);return '<div style="padding:10px 0;border-bottom:1px solid #edf1f5"><b style="font-size:12px">'+esc(l?l.code:"-")+' · '+esc(stageNames[e.type])+'</b><div style="font-size:11px;color:#718096;margin-top:4px">'+esc(e.date)+' · '+eventShort(e)+'</div></div>'}).join("")||'<div class="empty">공정 이력이 없습니다.</div>';var fd=state.events.filter(function(e){return e.type==="fdadm"&&n(e.data.admWeight)>0}),rat=[];fd.forEach(function(e){var l=findLot(e.lotId),a=n(e.data.sourceArea)||(l?n(l.measuredArea):0);if(a)rat.push(n(e.data.admWeight)/a)});areaWeightStats.innerHTML=rat.length?'<div style="font-size:28px;font-weight:800">'+fmt(rat.reduce(function(a,b){return a+b},0)/rat.length,3)+' g/cm²</div>':'<div class="empty">데이터가 쌓이면 표시됩니다.</div>';var cuts=state.events.filter(function(e){return e.type==="cutting"&&n(e.data.input)>0}),frees=state.events.filter(function(e){return e.type==="freezer"&&n(e.data.input)>0});function avg(a,fn){return a.length?a.reduce(function(s,e){return s+fn(e)},0)/a.length:0}millStats.innerHTML=(cuts.length||frees.length)?'<div class="statline"><span class="pill">Cutting '+(cuts.length?fmt(avg(cuts,function(e){return pct(n(e.data.output),n(e.data.input))})):"-")+'%</span><span class="pill">Freezer '+(frees.length?fmt(avg(frees,function(e){return pct(n(e.data.g70)+n(e.data.g100)+n(e.data.g500),n(e.data.input))})):"-")+'%</span></div>':'<div class="empty">분쇄 데이터를 등록하면 표시됩니다.</div>'}
function renderLots(){var s=lotSearch.value.trim().toLowerCase(),cur=bankFilter.value,banks=Array.from(new Set(state.lots.map(function(x){return x.bank}))).sort();bankFilter.innerHTML='<option value="">전체 조직은행<[REDACTED]>'+banks.map(function(x){return "<option>"+esc(x)+"<[REDACTED]>"}).join("");if(banks.includes(cur))bankFilter.value=cur;lotRows.innerHTML=state.lots.filter(function(l){return (!s||l.code.toLowerCase().includes(s)||l.bank.toLowerCase().includes(s))&&(!bankFilter.value||l.bank===bankFilter.value)}).sort(function(a,b){return String(b.date).localeCompare(String(a.date))}).map(function(l){var p=pct(n(l.measuredArea),n(l.inboundArea)),th=(l.tMin||l.tMax)?fmt(l.tMin,2)+"~"+fmt(l.tMax,2)+" mm":"-";return '<tr><td><b>'+esc(l.code)+'</b></td><td>'+esc(l.bank)+'</td><td>'+esc(l.date)+'</td><td>'+fmt(l.inboundArea)+' cm²</td><td>'+(l.measuredArea?fmt(l.measuredArea)+" cm²":"-")+'</td><td>'+(l.measuredArea?'<span class="badge teal">'+fmt(p)+'%</span>':"-")+'</td><td>'+th+'</td><td>'+(photoCount(l)?'<span class="badge navy">'+photoCount(l)+'장 / 분석 '+analyzedPhotoCount(l)+'</span>':"-")+'</td><td><span class="badge navy">'+esc(latestStage(l.id))+'</span></td><td><button class="link" onclick="showDetail(\''+l.id+'\')">상세</button></td></tr>'}).join("")||'<tr><td colspan="10"><div class="empty">등록된 Lot이 없습니다.</div></td></tr>'}
lotSearch.oninput=renderLots;bankFilter.onchange=renderLots;
function renderProcessOptions(){var cur=pLot.value;pLot.innerHTML=state.lots.map(function(l){return '<option value="'+l.id+'">'+esc(l.code)+' · '+esc(l.bank)+'</option>'}).join("");if(state.lots.some(function(l){return l.id===cur}))pLot.value=cur;pDate.value=pDate.value||today();renderStageFields();updateProcessSide()}
pLot.onchange=updateProcessSide;pStage.onchange=renderStageFields;
function renderStageFields(){var s=pStage.value,h="";if(s==="sderm")h='<div class="form-grid"><div class="field"><label>제품</label><select id="sProduct"><option>S Derm HD<[REDACTED]><option>S Derm CP<[REDACTED]></select></div><div class="field"><label>투입면적 (cm²)</label><input class="input" id="sInput" type="number" step=".1"></div><div class="field"><label>생산면적 (cm²)</label><input class="input" id="sOutput" type="number" step=".1"></div><div class="field"><label>잔여면적 (cm²)</label><input class="input" id="sRemain" type="number" step=".1"></div></div>';else if(s==="fdadm")h='<div class="form-grid"><div class="field"><label>FD 생산 여부</label><select id="fHas"><option value="yes">FD 생산<[REDACTED]><option value="no">FD 미생산<[REDACTED]></select></div><div class="field"><label>해당 원재료 면적</label><input class="input" id="fSourceArea" type="number" step=".1"></div><div class="field"><label>FD 생산면적</label><input class="input" id="fFdArea" type="number" step=".1"></div><div class="field"><label>ADM 중량 (g)</label><input class="input" id="fAdmWeight" type="number" step=".01"></div></div>';else if(s==="cutting")h='<div class="form-grid"><div class="field"><label>투입중량 (g)</label><input class="input" id="cInput" type="number" step=".01"></div><div class="field"><label>회수중량 (g)</label><input class="input" id="cOutput" type="number" step=".01"></div></div>';else if(s==="freezer")h='<div class="form-grid"><div class="field"><label>투입중량</label><input class="input" id="zInput" type="number" step=".01"></div><div class="field"><label>70 µm 이하 (g)</label><input class="input" id="z70" type="number" step=".01"></div><div class="field"><label>100 µm 이하 (g)</label><input class="input" id="z100" type="number" step=".01"></div><div class="field"><label>500 µm 이하 (g)</label><input class="input" id="z500" type="number" step=".01"></div></div>';else h='<div class="form-grid"><div class="field"><label>최종제품</label><select id="xProduct"><option>S Gen<[REDACTED]><option>S Gen Inject<[REDACTED]><option>Adite<[REDACTED]><option>MedPark Fill<[REDACTED]></select></div><div class="field"><label>용량 (cc)</label><select id="xVol"><option>0.5<[REDACTED]><option>1<[REDACTED]><option>2<[REDACTED]><option>3<[REDACTED]><option>5<[REDACTED]></select></div><div class="field"><label>Powder Grade</label><select id="xGrade"><option value="70">70 µm 이하<[REDACTED]><option value="100">100 µm 이하<[REDACTED]><option value="500">500 µm 이하<[REDACTED]></select></div><div class="field"><label>Powder 사용량</label><input class="input" id="xPowder" type="number" step=".01"></div><div class="field"><label>생산수량</label><input class="input" id="xQty" type="number"></div><div class="field"><label>필요 규격</label><input class="input" id="xRequired" readonly></div></div><div id="ruleCheck" class="notice" style="margin-top:10px"></div>';stageFields.innerHTML=h;if(s==="final"){xProduct.onchange=checkRule;xVol.onchange=checkRule;xGrade.onchange=checkRule;checkRule()}}
function requiredGrade(p,v){if(p==="S Gen")return"500";if(p==="Adite")return"70";if(p==="S Gen Inject")return String(v)==="0.5"?"70":"100";if(p==="MedPark Fill")return String(v)==="0.5"?"70":"100";return""}
function checkRule(){var r=requiredGrade(xProduct.value,xVol.value);xRequired.value=r+" µm 이하 Grade";ruleCheck.className=xGrade.value===r?"notice":"warnbox";ruleCheck.innerHTML=xGrade.value===r?"규격 적합":"규격 불일치: <b>"+r+" µm 이하</b>가 기준입니다."}
saveProcess.onclick=function(){var lotId=pLot.value;if(!lotId){alert("Lot을 먼저 등록해 주세요.");return}var type=pStage.value,data={operator:pOperator.value.trim()},date=pDate.value||today();if(type==="sderm"){data.product=sProduct.value;data.input=n(sInput.value);data.output=n(sOutput.value);data.remain=n(sRemain.value)}else if(type==="fdadm"){data.hasFd=fHas.value;data.sourceArea=n(fSourceArea.value);data.fdArea=n(fFdArea.value);data.admWeight=n(fAdmWeight.value)}else if(type==="cutting"){data.input=n(cInput.value);data.output=n(cOutput.value)}else if(type==="freezer"){data.input=n(zInput.value);data.g70=n(z70.value);data.g100=n(z100.value);data.g500=n(z500.value)}else{data.product=xProduct.value;data.volume=xVol.value;data.grade=xGrade.value;data.powder=n(xPowder.value);data.qty=n(xQty.value);data.required=requiredGrade(data.product,data.volume);if(data.grade!==data.required&&!confirm("제품 규격 기준과 다릅니다. 저장할까요?"))return}state.events.push({id:id("ev"),lotId:lotId,type:type,date:date,data:data,createdAt:new Date().toISOString()});saveState();alert("공정 이력이 저장되었습니다.")};
function eventShort(e){var d=e.data||{};if(e.type==="sderm")return esc(d.product)+" "+fmt(d.output)+" cm² / "+fmt(pct(d.output,d.input))+"%";if(e.type==="fdadm")return (d.hasFd==="yes"?"FD "+fmt(d.fdArea)+" cm² · ":"")+"ADM "+fmt(d.admWeight)+" g";if(e.type==="cutting")return fmt(d.input)+" → "+fmt(d.output)+" g";if(e.type==="freezer")return "70:"+fmt(d.g70)+"g · 100:"+fmt(d.g100)+"g · 500:"+fmt(d.g500)+"g";if(e.type==="final")return esc(d.product)+" "+esc(d.volume)+"cc · "+fmt(d.qty,0)+" ea";return""}
function updateProcessSide(){var l=findLot(pLot.value);selectedLotName.textContent=l?l.code:"-";if(!l){selectedSummary.innerHTML='<div class="empty">Lot을 먼저 등록해 주세요.</div>';selectedTimeline.innerHTML="";return}var av=(n(l.tMin)+n(l.tMax))/2;selectedSummary.innerHTML='<div class="detail-grid"><div class="detail-box"><small>입고면적</small><b>'+fmt(l.inboundArea)+' cm²</b></div><div class="detail-box"><small>확정 실측</small><b>'+(l.measuredArea?fmt(l.measuredArea)+" cm²":"-")+'</b></div><div class="detail-box"><small>평균두께</small><b>'+((l.tMin||l.tMax)?fmt(av,2)+" mm":"-")+'</b></div><div class="detail-box"><small>현재단계</small><b>'+esc(latestStage(l.id))+'</b></div></div>';var h='<div class="t-item"><b>원재료 입고</b><small>'+esc(l.date)+' · '+fmt(l.inboundArea)+' cm²</small></div>';lotEvents(l.id).forEach(function(e){h+='<div class="t-item"><b>'+esc(stageNames[e.type])+'</b><small>'+esc(e.date)+' · '+eventShort(e)+'</small></div>'});selectedTimeline.innerHTML=h}
function renderPhotoCard(lid,p,type){var sub=p.analysis&&p.analysis.areaCm2?"분석 "+fmt(p.analysis.areaCm2)+" cm² · "+(p.analysis.confidence||"-"):"미분석";return '<div class="photo-card"><img src="'+p.dataUrl+'"><div class="meta"><b>'+esc(p.name)+'</b><small>'+sub+'</small><div class="photo-actions">'+(type==="actual"?'<button class="btn soft" onclick="openAnalysis(\''+lid+'\',\''+p.id+'\')">면적 분석</button><button class="btn" onclick="applyPhotoArea(\''+lid+'\',\''+p.id+'\')">실측 반영</button>':'<span class="badge">Map 보관</span>')+'</div></div></div>'}
function showDetail(lid){var l=findLot(lid);if(!l)return;currentDetailLot=lid;detailTitle.textContent=l.code+" 상세 이력";var th=(l.tMin||l.tMax)?fmt(l.tMin,2)+"~"+fmt(l.tMax,2)+" mm":"-",p=l.measuredArea?pct(l.measuredArea,l.inboundArea):0,es=lotEvents(lid),h='<div class="detail-grid"><div class="detail-box"><small>조직은행</small><b>'+esc(l.bank)+'</b></div><div class="detail-box"><small>입고면적</small><b>'+fmt(l.inboundArea)+' cm²</b></div><div class="detail-box"><small>확정 실측면적</small><b>'+(l.measuredArea?fmt(l.measuredArea)+" cm²":"-")+'</b></div><div class="detail-box"><small>실측률</small><b>'+(l.measuredArea?fmt(p)+"%":"-")+'</b></div><div class="detail-box"><small>Map 면적</small><b>'+(l.mapArea?fmt(l.mapArea)+" cm²":"-")+'</b></div><div class="detail-box"><small>두께</small><b>'+th+'</b></div><div class="detail-box"><small>실제사진</small><b>'+(l.actualPhotos||[]).length+' 장</b></div><div class="detail-box"><small>Map 사진</small><b>'+(l.mapPhotos||[]).length+' 장</b></div></div>';if(l.note)h+='<div class="notice" style="margin-bottom:18px">'+esc(l.note)+'</div>';h+='<div class="note-grid"><div><div class="section-title"><h3>실제 Skin 사진</h3><span>면적 분석</span></div><div class="gallery">'+((l.actualPhotos||[]).map(function(p){return renderPhotoCard(l.id,p,"actual")}).join("")||'<div class="empty">등록된 실제사진이 없습니다.</div>')+'</div></div><div><div class="section-title"><h3>Skin Map 사진</h3><span>보조 검증</span></div><div class="gallery">'+((l.mapPhotos||[]).map(function(p){return renderPhotoCard(l.id,p,"map")}).join("")||'<div class="empty">등록된 Map 사진이 없습니다.</div>')+'</div></div></div><div class="section-title" style="margin-top:18px"><h3>Lot Genealogy / 공정 이력</h3><span>'+es.length+'개 이벤트</span></div><div class="timeline"><div class="t-item"><b>원재료 입고</b><small>'+esc(l.date)+' · '+fmt(l.inboundArea)+' cm²</small></div>';es.forEach(function(e){h+='<div class="t-item"><b>'+esc(stageNames[e.type])+'</b><small>'+esc(e.date)+' · '+eventShort(e)+'</small></div>'});h+="</div>";detailBody.innerHTML=h;openModal("detailModal")}
window.showDetail=showDetail;window.applyPhotoArea=function(lid,pid){var l=findLot(lid),p=(l.actualPhotos||[]).find(function(x){return x.id===pid});if(!p||!p.analysis){alert("먼저 사진 분석을 저장해 주세요.");return}l.measuredArea=n(p.analysis.areaCm2);saveState();showDetail(lid)};
goProcess.onclick=function(){closeModal("detailModal");document.querySelector('.nav button[data-view="process"]').click();pLot.value=currentDetailLot||"";updateProcessSide()};
function resetMetrics(){["mScale","mArea","mWidth","mHeight","mPixels","mConfidence"].forEach(function(i){document.getElementById(i).textContent="-"})}
function openAnalysis(lid,pid){var l=findLot(lid),p=(l.actualPhotos||[]).find(function(x){return x.id===pid});if(!p)return;analysisCtx={lotId:lid,photoId:pid,img:null,points:[],showMask:true,mask:null,last:p.analysis||null};analysisTitle.textContent=l.code+" · "+p.name+" 면적 분석";analysisNote.value=p.analysis&&p.analysis.note||"";calibMm.value=p.analysis&&p.analysis.calibrationMm||300;thresholdRange.value=p.analysis&&p.analysis.threshold||45;minAreaPx.value=p.analysis&&p.analysis.minAreaPx||1200;resetMetrics();var im=new Image();im.onload=function(){analysisCtx.img=im;if(p.analysis&&p.analysis.pointA&&p.analysis.pointB)analysisCtx.points=[p.analysis.pointA,p.analysis.pointB];if(p.analysis&&p.analysis.mask){analysisCtx.mask=p.analysis.mask;updateMetrics(p.analysis)}drawAnalysisCanvas()};im.src=p.dataUrl;openModal("analysisModal")}
window.openAnalysis=openAnalysis;
function drawAnalysisCanvas(){var c=analysisCanvas,ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);if(!analysisCtx.img)return;var im=analysisCtx.img,sc=Math.min(c.width/im.width,c.height/im.height),w=im.width*sc,h=im.height*sc,ox=(c.width-w)/2,oy=(c.height-h)/2;analysisCtx.draw={scale:sc,ox:ox,oy:oy,w:w,h:h};ctx.drawImage(im,ox,oy,w,h);if(analysisCtx.showMask&&analysisCtx.mask){var m=analysisCtx.mask;ctx.fillStyle="rgba(0,200,120,.35)";m.pixels.forEach(function(pt){ctx.fillRect(ox+pt.x*sc,oy+pt.y*sc,Math.max(1,sc),Math.max(1,sc))});ctx.strokeStyle="#ff4b4b";ctx.lineWidth=2;ctx.strokeRect(ox+m.bbox.minX*sc,oy+m.bbox.minY*sc,(m.bbox.maxX-m.bbox.minX+1)*sc,(m.bbox.maxY-m.bbox.minY+1)*sc)}analysisCtx.points.forEach(function(p,i){ctx.beginPath();ctx.fillStyle=i?"#00b96b":"#1f6fff";ctx.arc(ox+p.x*sc,oy+p.y*sc,6,0,Math.PI*2);ctx.fill()});if(analysisCtx.points.length===2){ctx.strokeStyle="#1f6fff";ctx.beginPath();ctx.moveTo(ox+analysisCtx.points[0].x*sc,oy+analysisCtx.points[0].y*sc);ctx.lineTo(ox+analysisCtx.points[1].x*sc,oy+analysisCtx.points[1].y*sc);ctx.stroke()}}
analysisCanvas.onclick=function(e){if(!analysisCtx.img)return;var r=this.getBoundingClientRect(),x=(e.clientX-r.left)*(this.width/r.width),y=(e.clientY-r.top)*(this.height/r.height),d=analysisCtx.draw;if(x<d.ox||x>d.ox+d.w||y<d.oy||y>d.oy+d.h)return;if(analysisCtx.points.length>=2)analysisCtx.points=[];analysisCtx.points.push({x:(x-d.ox)/d.scale,y:(y-d.oy)/d.scale});drawAnalysisCanvas()};
resetPointsBtn.onclick=function(){analysisCtx.points=[];analysisCtx.mask=null;analysisCtx.last=null;resetMetrics();drawAnalysisCanvas()};toggleMaskBtn.onclick=function(){analysisCtx.showMask=!analysisCtx.showMask;drawAnalysisCanvas()};
function distRGB(a,b){var r=a[0]-b[0],g=a[1]-b[1],d=a[2]-b[2];return Math.sqrt(r*r+g*g+d*d)}
function avgCornerBg(data,w,h){var sm=[0,0,0],cnt=0,z=Math.max(8,Math.floor(Math.min(w,h)*.05)),cs=[[0,0],[w-z,0],[0,h-z],[w-z,h-z]];cs.forEach(function(c){for(var y=c[1];y<c[1]+z;y+=2)for(var x=c[0];x<c[0]+z;x+=2){var i=(y*w+x)*4;sm[0]+=data[i];sm[1]+=data[i+1];sm[2]+=data[i+2];cnt++}});return sm.map(function(v){return v/cnt})}
function sat(r,g,b){var mx=Math.max(r,g,b),mn=Math.min(r,g,b);return mx?((mx-mn)/mx*255):0}
function runSegmentation(){if(!analysisCtx.img||analysisCtx.points.length!==2){alert("먼저 자 기준점 두 개를 찍어 주세요.");return}var mm=n(calibMm.value),thr=n(thresholdRange.value),min=n(minAreaPx.value)||1200;if(mm<=0)return alert("기준 길이를 입력해 주세요.");var im=analysisCtx.img,c=document.createElement("canvas");c.width=im.width;c.height=im.height;var cx=c.getContext("2d");cx.drawImage(im,0,0);var D=cx.getImageData(0,0,c.width,c.height).data,w=c.width,h=c.height,bg=avgCornerBg(D,w,h),mask=new Uint8Array(w*h);for(var y=0;y<h;y++)for(var x=0;x<w;x++){var i=(y*w+x)*4,r=D[i],g=D[i+1],b=D[i+2],br=(r+g+b)/3,is=(distRGB([r,g,b],bg)>thr)||(sat(r,g,b)>48&&br<240)||(r>g+12&&r>b+8&&br<240);mask[y*w+x]=is?1:0}var vis=new Uint8Array(w*h),best=null,qx=new Int32Array(w*h),qy=new Int32Array(w*h),cx0=w/2,cy0=h/2;for(var yy=1;yy<h-1;yy++)for(var xx=1;xx<w-1;xx++){var ii=yy*w+xx;if(!mask[ii]||vis[ii])continue;var head=0,tail=0;qx[tail]=xx;qy[tail]=yy;tail++;vis[ii]=1;var pix=[],minX=xx,maxX=xx,minY=yy,maxY=yy;while(head<tail){var X=qx[head],Y=qy[head];head++;pix.push({x:X,y:Y});if(X<minX)minX=X;if(X>maxX)maxX=X;if(Y<minY)minY=Y;if(Y>maxY)maxY=Y;var ns=[[1,0],[-1,0],[0,1],[0,-1]];for(var k=0;k<4;k++){var nx=X+ns[k][0],ny=Y+ns[k][1],ni=ny*w+nx;if(nx<=0||ny<=0||nx>=w-1||ny>=h-1)continue;if(mask[ni]&&!vis[ni]){vis[ni]=1;qx[tail]=nx;qy[tail]=ny;tail++}}}if(pix.length<min)continue;var score=pix.length-(Math.abs((minX+maxX)/2-cx0)+Math.abs((minY+maxY)/2-cy0))*.8;if(!best||score>best.score)best={pixels:pix,bbox:{minX:minX,maxX:maxX,minY:minY,maxY:maxY},score:score}}if(!best)return alert("외곽선을 찾지 못했습니다. 민감도를 조정해 주세요.");var a=analysisCtx.points[0],b=analysisCtx.points[1],px=Math.hypot(b.x-a.x,b.y-a.y),mpp=mm/px,area=best.pixels.length*mpp*mpp/100,wm=(best.bbox.maxX-best.bbox.minX+1)*mpp,hm=(best.bbox.maxY-best.bbox.minY+1)*mpp,fill=best.pixels.length/((best.bbox.maxX-best.bbox.minX+1)*(best.bbox.maxY-best.bbox.minY+1)),conf=fill>.65?"높음":fill>.45?"중간":"낮음";analysisCtx.mask={pixels:best.pixels.slice(0,60000),bbox:best.bbox};analysisCtx.last={areaCm2:Math.round(area*10)/10,widthMm:Math.round(wm),heightMm:Math.round(hm),pixelCount:best.pixels.length,mmPerPx:mpp,confidence:conf,threshold:thr,minAreaPx:min,calibrationMm:mm,pointA:a,pointB:b,mask:analysisCtx.mask,note:analysisNote.value.trim()};updateMetrics(analysisCtx.last);drawAnalysisCanvas()}
function updateMetrics(r){mScale.textContent=fmt(r.mmPerPx,3)+" mm/px";mArea.textContent=fmt(r.areaCm2)+" cm²";mWidth.textContent=fmt(r.widthMm,0)+" mm";mHeight.textContent=fmt(r.heightMm,0)+" mm";mPixels.textContent=fmt(r.pixelCount,0)+" px";mConfidence.textContent=r.confidence||"-"}
runSegBtn.onclick=runSegmentation;saveAnalysisBtn.onclick=function(){if(!analysisCtx.last)return alert("먼저 분석을 실행해 주세요.");var l=findLot(analysisCtx.lotId),p=(l.actualPhotos||[]).find(function(x){return x.id===analysisCtx.photoId});p.analysis=JSON.parse(JSON.stringify(analysisCtx.last));saveState();alert("사진 분석을 저장했습니다.");closeModal("analysisModal");showDetail(l.id)};applyMeasuredBtn.onclick=function(){if(!analysisCtx.last)return alert("먼저 분석을 실행해 주세요.");var l=findLot(analysisCtx.lotId),p=(l.actualPhotos||[]).find(function(x){return x.id===analysisCtx.photoId});p.analysis=JSON.parse(JSON.stringify(analysisCtx.last));l.measuredArea=n(analysisCtx.last.areaCm2);saveState();alert("Lot 확정 실측면적에 반영했습니다.");closeModal("analysisModal");showDetail(l.id)};
demoBtn.onclick=function(){if(state.lots.length&&!confirm("현재 데이터가 있습니다. 샘플 데이터를 추가할까요?"))return;var a={id:id("lot"),code:"SK260901-A01",bank:"Tissue Bank A",date:"2026-09-01",inboundArea:850,measuredArea:735,mapArea:750,tMin:3.6,tMax:3.9,note:"샘플 Lot",actualPhotos:[],mapPhotos:[],createdAt:new Date().toISOString()};state.lots.push(a);saveState()};
function renderAll(){renderDashboard();renderLots();renderProcessOptions()} renderAll();