(function(){
  'use strict';
  var originalOpenAnalysis=window.openAnalysis,originalShowDetail=window.showDetail,originalRenderAll=window.renderAll;
  function compactAnalysis(r){if(!r)return null;return {areaCm2:n(r.areaCm2),widthMm:n(r.widthMm),heightMm:n(r.heightMm),pixelCount:n(r.pixelCount),mmPerPx:n(r.mmPerPx),confidence:r.confidence||'-',threshold:n(r.threshold),minAreaPx:n(r.minAreaPx),calibrationMm:n(r.calibrationMm),pointA:r.pointA||null,pointB:r.pointB||null,note:r.note||'',savedAt:r.savedAt||new Date().toISOString(),version:r.version||1}}
  function latestVersion(photo){if(photo&&photo.analyses&&photo.analyses.length)return photo.analyses[photo.analyses.length-1];return photo&&photo.analysis?compactAnalysis(photo.analysis):null}
  function migrateAnalyses(){var changed=false;(state.lots||[]).forEach(function(l){l.actualPhotos=l.actualPhotos||[];l.mapPhotos=l.mapPhotos||[];l.actualPhotos.forEach(function(p){if(!p.analyses)p.analyses=[];if(p.analysis&&p.analyses.length===0){var c=compactAnalysis(p.analysis);c.version=1;p.analyses.push(c);changed=true}})});if(changed){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}}
  function storageUsageKb(){try{return Math.round((localStorage.getItem(KEY)||'').length*2/1024)}catch(e){return 0}}
  function updateStorageBadge(){var el=document.getElementById('storageUsageV3');if(el)el.textContent='브라우저 저장 약 '+storageUsageKb().toLocaleString('ko-KR')+' KB'}
  function safeSaveState(){try{localStorage.setItem(KEY,JSON.stringify(state));if(typeof originalRenderAll==='function')originalRenderAll();else if(typeof renderAll==='function')renderAll();updateStorageBadge();return true}catch(e){alert('브라우저 저장공간이 부족합니다. 사진 수가 많아지면 운영형 서버/Object Storage 저장이 필요합니다.');return false}}
  window.saveState=safeSaveState;
  function ensureAdvancedUi(){var reset=document.getElementById('resetPointsBtn');if(reset&&!document.getElementById('autoRulerBtn')){var b=document.createElement('button');b.id='autoRulerBtn';b.className='btn soft';b.textContent='자 후보 자동탐색';b.onclick=autoDetectRulerCandidate;reset.parentNode.insertBefore(b,reset)}var metrics=document.querySelector('#analysisModal .analysis-metrics');if(metrics&&!document.getElementById('analysisHistoryBox')){var box=document.createElement('div');box.id='analysisHistoryBox';box.className='notice';box.innerHTML='<b>분석 이력</b><div id="analysisHistoryList" style="margin-top:8px">저장된 분석이 없습니다.</div>';metrics.parentNode.insertBefore(box,metrics.nextSibling)}var toolbox=document.querySelector('#analysisModal .toolbox');if(toolbox&&!document.getElementById('autoRulerHelp')){var h=document.createElement('div');h.id='autoRulerHelp';h.className='warnbox';h.innerHTML='<b>자 자동탐색은 후보 제시 기능입니다.</b><br>파란 기준선이 실제 자의 기준 구간과 다르면 사진을 직접 두 번 클릭해 기준점을 다시 지정하세요.';toolbox.insertBefore(h,toolbox.children[1]||null)}}
  function grayImage(img,maxDim){var scale=Math.min(1,(maxDim||700)/Math.max(img.width,img.height)),w=Math.max(20,Math.round(img.width*scale)),h=Math.max(20,Math.round(img.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;var cx=c.getContext('2d');cx.drawImage(img,0,0,w,h);var d=cx.getImageData(0,0,w,h).data,g=new Float32Array(w*h);for(var i=0,j=0;i<d.length;i+=4,j++)g[j]=0.299*d[i]+0.587*d[i+1]+0.114*d[i+2];return {g:g,w:w,h:h,scale:scale}}
  function edgeColumnScore(G,x){var s=0,w=G.w,h=G.h,g=G.g;x=Math.max(1,Math.min(w-2,x));for(var y=1;y<h-1;y+=2){var i=y*w+x;s+=Math.abs(g[i+1]-g[i-1])+0.4*Math.abs(g[i+w]-g[i-w])}return s/(h/2)}
  function edgeRowScore(G,y){var s=0,w=G.w,h=G.h,g=G.g;y=Math.max(1,Math.min(h-2,y));for(var x=1;x<w-1;x+=2){var i=y*w+x;s+=Math.abs(g[i+w]-g[i-w])+0.4*Math.abs(g[i+1]-g[i-1])}return s/(w/2)}
  function autoDetectRulerCandidate(){if(!analysisCtx||!analysisCtx.img){alert('먼저 분석할 사진을 열어 주세요.');return}var G=grayImage(analysisCtx.img,700),w=G.w,h=G.h,bestV={score:-1,x:0},bestH={score:-1,y:0};var zonesX=[];for(var x=2;x<Math.floor(w*.28);x++)zonesX.push(x);for(var x2=Math.ceil(w*.72);x2<w-2;x2++)zonesX.push(x2);zonesX.forEach(function(x){var s=edgeColumnScore(G,x);if(s>bestV.score)bestV={score:s,x:x}});var zonesY=[];for(var y=2;y<Math.floor(h*.28);y++)zonesY.push(y);for(var y2=Math.ceil(h*.72);y2<h-2;y2++)zonesY.push(y2);zonesY.forEach(function(y){var s=edgeRowScore(G,y);if(s>bestH.score)bestH={score:s,y:y}});var inv=1/G.scale;if(bestV.score>=bestH.score)analysisCtx.points=[{x:bestV.x*inv,y:h*.10*inv},{x:bestV.x*inv,y:h*.90*inv}];else analysisCtx.points=[{x:w*.10*inv,y:bestH.y*inv},{x:w*.90*inv,y:bestH.y*inv}];var mm=document.getElementById('calibMm');mm.value=mm.value||300;if(typeof drawAnalysisCanvas==='function')drawAnalysisCanvas();alert('자 후보 기준선을 표시했습니다. 실제 자의 기준 구간과 맞는지 확인하세요. 다르면 사진을 직접 클릭해 기준점을 다시 지정할 수 있습니다.')}
  window.autoDetectRulerCandidate=autoDetectRulerCandidate;
  function populateHistory(photo){var el=document.getElementById('analysisHistoryList');if(!el)return;var arr=(photo&&photo.analyses)||[];if(!arr.length){el.innerHTML='저장된 분석이 없습니다.';return}el.innerHTML=arr.slice().reverse().map(function(a){var when=a.savedAt?new Date(a.savedAt).toLocaleString('ko-KR'):'-';return '<div style="padding:7px 0;border-bottom:1px solid #dceae8"><b>v'+esc(a.version||1)+'</b> · '+fmt(a.areaCm2)+' cm² · '+esc(a.confidence||'-')+'<br><span style="font-size:10px;color:#6b778c">'+esc(when)+(a.note?' · '+esc(a.note):'')+'</span></div>'}).join('')}
  window.openAnalysis=function(lid,pid){originalOpenAnalysis(lid,pid);ensureAdvancedUi();var lot=findLot(lid),photo=lot&&(lot.actualPhotos||[]).find(function(p){return p.id===pid});populateHistory(photo);var last=latestVersion(photo);if(last){analysisCtx.last=Object.assign({},last,{mask:null});setTimeout(function(){if(typeof updateMetrics==='function')updateMetrics(last)},0)}};
  function saveVersion(applyMeasured){if(!analysisCtx||!analysisCtx.last){alert('먼저 분석을 실행해 주세요.');return}var lot=findLot(analysisCtx.lotId);if(!lot)return;var photo=(lot.actualPhotos||[]).find(function(p){return p.id===analysisCtx.photoId});if(!photo)return;photo.analyses=photo.analyses||[];var compact=compactAnalysis(analysisCtx.last);compact.version=photo.analyses.length+1;compact.savedAt=new Date().toISOString();compact.note=document.getElementById('analysisNote').value.trim();photo.analyses.push(compact);photo.analysis=compact;if(applyMeasured)lot.measuredArea=n(compact.areaCm2);if(!safeSaveState())return;alert(applyMeasured?'분석을 저장하고 Lot 확정 실측면적에 반영했습니다.':'사진 분석을 버전 이력으로 저장했습니다.');closeModal('analysisModal');window.showDetail(lot.id)}
  function overrideAnalysisButtons(){var s=document.getElementById('saveAnalysisBtn'),a=document.getElementById('applyMeasuredBtn');if(s)s.onclick=function(){saveVersion(false)};if(a)a.onclick=function(){saveVersion(true)}}
  function addLotComparison(lid){var lot=findLot(lid),body=document.getElementById('detailBody');if(!lot||!body)return;var map=n(lot.mapArea),meas=n(lot.measuredArea),diff=meas-map,ratio=map?pct(meas,map):0,versions=(lot.actualPhotos||[]).reduce(function(s,p){return s+((p.analyses||[]).length)},0),analyzed=analyzedPhotoCount(lot);var html='<div class="card section" style="margin-bottom:18px;background:#fbfefd"><div class="section-title"><h3>사진 · Map 비교</h3><span id="storageUsageV3"></span></div><div class="detail-grid"><div class="detail-box"><small>Map 추정면적</small><b>'+(map?fmt(map)+' cm²':'-')+'</b></div><div class="detail-box"><small>확정 실측면적</small><b>'+(meas?fmt(meas)+' cm²':'-')+'</b></div><div class="detail-box"><small>차이</small><b>'+(map&&meas?(diff>=0?'+':'')+fmt(diff)+' cm²':'-')+'</b></div><div class="detail-box"><small>실측 / Map</small><b>'+(map&&meas?fmt(ratio)+'%':'-')+'</b></div><div class="detail-box"><small>실제사진</small><b>'+(lot.actualPhotos||[]).length+' 장</b></div><div class="detail-box"><small>분석 완료 사진</small><b>'+analyzed+' 장</b></div><div class="detail-box"><small>분석 버전</small><b>'+versions+' 회</b></div><div class="detail-box"><small>두께</small><b>'+((lot.tMin||lot.tMax)?fmt(lot.tMin,2)+'~'+fmt(lot.tMax,2)+' mm':'-')+'</b></div></div><div class="notice">Map은 보조 기준이고, 확정 실측면적은 실제사진 분석 후 작업자가 확인한 값을 사용합니다. 분석을 다시 수행해도 이전 버전은 이력으로 남습니다.</div></div>';body.insertAdjacentHTML('afterbegin',html);updateStorageBadge()}
  window.showDetail=function(lid){originalShowDetail(lid);addLotComparison(lid)};
  function addDashboardNote(){var d=document.getElementById('dashboard');if(!d||document.getElementById('v3FeatureNote'))return;var note=document.createElement('div');note.id='v3FeatureNote';note.className='notice';note.style.marginTop='16px';note.innerHTML='<b>3차 고도화 활성</b> · 자 후보 자동탐색, 분석 버전 이력, Map↔확정 실측 비교가 추가되었습니다. 자동 자 탐색 결과는 반드시 화면에서 확인 후 사용하세요.';d.appendChild(note)}
  migrateAnalyses();ensureAdvancedUi();overrideAnalysisButtons();addDashboardNote();updateStorageBadge();
})();